####开发环境配置
server:
  port: 7005

spring: 
#druid pgsql
  druid:  
    url: jdbc:mysql://192.168.1.101:3306/testDB?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 30 #最大连接数
    min-idle: 5 #最小连接数
    max-wait: 10000 #获取连接的最大等待时间
    time-between-eviction-runs-millis: 60000 #空闲连接的检查时间间隔
    min-evictable-idle-time-millis: 300000 #空闲连接最小空闲时间

#redis
  redis:
    database: 9
    host: 192.168.1.101
    port: 6379
    password: 123456
    timeout: 6000
    expire: 1800
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 100
        max-wait: -1