server:
  port: 7005
  tomcat: 
    basedir: /tmp/

spring:
  application:
    name : micro-svc-demo1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet: 
    multipart: 
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  main: 
    allow-bean-definition-overriding: true
      
## 环境配置文件 dev test show prod
  profiles:
    active: "@spring.profiles.active@"

## Mybatis config
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:mybatis.xml

## pagehelper
pagehelper: 
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: countSql
  count: countSql
  returnPageInfo: check

## 记录日志
logging: 
  config: classpath:logback-spring.xml
## Start logging
  level: 
    root: INFO
