server:
  port: 7005
  
eureka: 
  instance:
   # hostname: eureka.test.com
    port: 7001 
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5  ## 心跳间隔，5秒
    lease-expiration-duration-in-seconds: 10 ## 没有心跳的淘汰时间，10秒
  client: 
    registry-fetch-interval-seconds: 5 # 定时刷新本地缓存时间
    service-url: 
      defaultZone: http://${spring.cloud.client.ip-address}:${eureka.instance.port}/eureka/

info: 
  app.name: micro-svc-demo1
  company.name: test.com
  build.groupId: "@project.parent.groupId@" ##yml文件用@，properties文件用$ resource.filtering必须设置为true
  build.artifactId: "@project.artifactId@"
  build.version: "@project.parent.version@"

spring: 
#druid pgsql
  druid:  
    url: jdbc:mysql://192.168.1.101:3306/testDB?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 30 #最大连接数
    min-idle: 5 #最小连接数
    max-wait: 10000 #获取连接的最大等待时间
    time-between-eviction-runs-millis: 60000 #空闲连接的检查时间间隔
    min-evictable-idle-time-millis: 300000 #空闲连接最小空闲时间

#redis
  redis:
    database: 12
    host: 192.168.1.101
    port: 6379
    password: 123456
    timeout: 6000
    expire: 1800
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 100
        max-wait: -1
 
  