####开发环境配置
server:
  port: 7004

spring: 
#druid pgsql
  druid:  
    url: jdbc:postgresql://127.0.0.1:5432/test?tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
    max-active: 30 #最大连接数
    min-idle: 5 #最小连接数
    max-wait: 10000 #获取连接的最大等待时间
    time-between-eviction-runs-millis: 60000 #空闲连接的检查时间间隔
    min-evictable-idle-time-millis: 300000 #空闲连接最小空闲时间

#redis
  redis:
    database: 9
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000
    expire: 1800
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 100
        max-wait: -1